services:

  controller.homepage_controller:
    class: Kutny\FrontBundle\Controller\HomepageController

  controller.symfony_training_controller:
    class: Kutny\FrontBundle\Controller\SymfonyTrainingController