services:

  assets.asset_url_extension:
    class: KutnyLib\Assets\AssetUrlExtension
    arguments: [%asset_version%]
    tags:
      - { name: twig.extension }

  controller.homepage_controller:
    class: Kutny\FrontBundle\Controller\HomepageController

  controller.symfony_training_controller:
    class: Kutny\FrontBundle\Controller\SymfonyTrainingController

  menu_builder:
    class: Kutny\FrontBundle\Menu\MainMenuBuilder
    arguments: [@knp_menu.factory]

  menu.main:
    class: Knp\Menu\MenuItem
    factory_service: menu_builder
    factory_method: createMainMenu
    arguments: [@request]
    scope: request # needed as we have the request as a dependency here
    tags:
      - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu